platform :ios,'8.0'
target 'QQMusic' do
pod 'ReactiveCocoa', '~>2.5'
pod 'Masonry'
pod 'YYModel'
pod 'AFNetworking'
pod 'YYText'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'MJExtension'
pod 'SVProgressHUD'
pod 'FMDB'
end 

